var fx_options = {
"0": [{container: "si_800001C4",plugin: "animation",option: {}},
{container: "si_800001C7",plugin: "animation",option: {}},
{container: "si_800001CA",plugin: "animation",option: {}},
{container: "si_800001CD",plugin: "animation",option: {}},
{container: "si_800001D0",plugin: "animation",option: {}},
{container: "si_800001D3",plugin: "animation",option: {}},
{container: "si_80000179",plugin: "animation",option: {}},
{container: "si_80000173",plugin: "animation",option: {}},
{container: "si_80000170",plugin: "animation",option: {}},
{container: "si_80000176",plugin: "animation",option: {}},
{container: "si_800001D6",plugin: "animation",option: {}},
{container: "buttonItem-18",plugin: "button",option: {}},
{container: "si_800001D9",plugin: "animation",option: {}},
{container: "buttonItem-19",plugin: "button",option: {}},
],
"1": [{container: "si_8000029C",plugin: "animation",option: {}},
{container: "si_8000024D",plugin: "animation",option: {}},
{container: "si_800003A0",plugin: "animation",option: {}},
{container: "si_800003A3",plugin: "animation",option: {}},
{container: "si_8000039C",plugin: "animation",option: {}},
{container: "buttonItem-58",plugin: "button",option: {}},
],
"2": [{container: "si_80000368",plugin: "animation",option: {}},
{container: "si_800003ED",plugin: "animation",option: {}},
{container: "si_80000335",plugin: "animation",option: {}},
{container: "si_8000036E",plugin: "animation",option: {}},
{container: "buttonItem-100",plugin: "button",option: {}},
{container: "si_80000369",plugin: "animation",option: {}},
{container: "si_80000320",plugin: "animation",option: {}},
{container: "buttonItem-101",plugin: "button",option: {}},
{container: "si_8000030F",plugin: "popupContent",option: {}},
{container: "imagePanItem-95",plugin: "imagePan",option: {}},
{container: "imagePanItem-96",plugin: "imagePan",option: {}},
{container: "imagePanItem-97",plugin: "imagePan",option: {}},
{container: "imagePanItem-98",plugin: "imagePan",option: {}},
{container: "imagePanItem-99",plugin: "imagePan",option: {}},
{container: "si_8000047A",plugin: "animation",option: {}},
{container: "imageItem-90",plugin: "gif",option: {}},
{container: "si_80000354",plugin: "animation",option: {}},
{container: "si_8000031A",plugin: "animation",option: {}},
{container: "buttonItem-102",plugin: "button",option: {}},
{container: "si_80000319",plugin: "animation",option: {}},
{container: "buttonItem-103",plugin: "button",option: {}},
{container: "si_80000269",plugin: "animation",option: {}},
{container: "buttonItem-104",plugin: "button",option: {}},
],
"3": [{container: "si_800002AE",plugin: "animation",option: {}},
{container: "imageItem-141",plugin: "gif",option: {}},
{container: "si_8000078B",plugin: "animation",option: {}},
{container: "buttonItem-154",plugin: "button",option: {}},
{container: "si_800004B2",plugin: "animation",option: {}},
{container: "buttonItem-155",plugin: "button",option: {}},
{container: "si_80000789",plugin: "animation",option: {}},
{container: "buttonItem-156",plugin: "button",option: {}},
{container: "si_8000032B",plugin: "popupContent",option: {}},
{container: "buttonItem-157",plugin: "button",option: {}},
{container: "buttonItem-158",plugin: "button",option: {}},
{container: "si_800002C9",plugin: "animation",option: {}},
{container: "si_80000347",plugin: "animation",option: {}},
{container: "si_80000348",plugin: "animation",option: {}},
{container: "si_80000261",plugin: "animation",option: {}},
{container: "si_800004A9",plugin: "animation",option: {}},
],
"4": [{container: "si_8000068E",plugin: "animation",option: {}},
{container: "buttonItem-202",plugin: "button",option: {}},
{container: "si_80000782",plugin: "animation",option: {}},
{container: "buttonItem-203",plugin: "button",option: {}},
{container: "si_800004C0",plugin: "animation",option: {}},
{container: "buttonItem-204",plugin: "button",option: {}},
{container: "si_800004D7",plugin: "animation",option: {}},
{container: "imageItem-192",plugin: "gif",option: {}},
{container: "si_800004D3",plugin: "popupContent",option: {}},
{container: "buttonItem-205",plugin: "button",option: {}},
{container: "buttonItem-206",plugin: "button",option: {}},
{container: "si_800004BD",plugin: "animation",option: {}},
{container: "si_800004BE",plugin: "animation",option: {}},
{container: "si_800004B9",plugin: "animation",option: {}},
{container: "si_800004B6",plugin: "animation",option: {}},
{container: "si_800004BF",plugin: "animation",option: {}},
],
"5": [{container: "imageItem-237",plugin: "gif",option: {}},
{container: "buttonItem-246",plugin: "button",option: {}},
{container: "buttonItem-247",plugin: "button",option: {}},
{container: "si_8000032E",plugin: "animation",option: {}},
{container: "buttonItem-248",plugin: "button",option: {}},
{container: "si_80000349",plugin: "popupContent",option: {}},
{container: "buttonItem-249",plugin: "button",option: {}},
{container: "buttonItem-250",plugin: "button",option: {}},
{container: "si_8000012D",plugin: "animation",option: {}},
],
"6": [{container: "si_80000674",plugin: "animation",option: {}},
{container: "buttonItem-287",plugin: "button",option: {}},
{container: "si_800006D2",plugin: "animation",option: {}},
{container: "buttonItem-288",plugin: "button",option: {}},
{container: "si_80000386",plugin: "animation",option: {}},
{container: "imageItem-276",plugin: "gif",option: {}},
{container: "si_8000036C",plugin: "popupContent",option: {}},
{container: "buttonItem-289",plugin: "button",option: {}},
{container: "buttonItem-290",plugin: "button",option: {}},
{container: "si_80000484",plugin: "animation",option: {}},
{container: "buttonItem-291",plugin: "button",option: {}},
{container: "si_80000382",plugin: "animation",option: {}},
{container: "si_80000383",plugin: "animation",option: {}},
{container: "si_80000381",plugin: "animation",option: {}},
{container: "si_800003D0",plugin: "animation",option: {}},
{container: "si_8000046E",plugin: "animation",option: {}},
],
"7": [{container: "si_800006E3",plugin: "animation",option: {}},
{container: "buttonItem-335",plugin: "button",option: {}},
{container: "si_8000068D",plugin: "animation",option: {}},
{container: "buttonItem-336",plugin: "button",option: {}},
{container: "si_8000060A",plugin: "animation",option: {}},
{container: "imageItem-324",plugin: "gif",option: {}},
{container: "si_8000060B",plugin: "popupContent",option: {}},
{container: "buttonItem-337",plugin: "button",option: {}},
{container: "buttonItem-338",plugin: "button",option: {}},
{container: "si_80000612",plugin: "animation",option: {}},
{container: "buttonItem-339",plugin: "button",option: {}},
{container: "si_8000060C",plugin: "animation",option: {}},
{container: "si_8000060E",plugin: "animation",option: {}},
{container: "si_8000060F",plugin: "animation",option: {}},
{container: "si_80000610",plugin: "animation",option: {}},
{container: "si_80000611",plugin: "animation",option: {}},
],
"8": [{container: "imageItem-370",plugin: "gif",option: {}},
{container: "buttonItem-379",plugin: "button",option: {}},
{container: "buttonItem-380",plugin: "button",option: {}},
{container: "si_800005AB",plugin: "animation",option: {}},
{container: "buttonItem-381",plugin: "button",option: {}},
{container: "si_80000441",plugin: "popupContent",option: {}},
{container: "buttonItem-382",plugin: "button",option: {}},
{container: "buttonItem-383",plugin: "button",option: {}},
{container: "si_8000049D",plugin: "animation",option: {}},
],
"9": [{container: "si_80000641",plugin: "animation",option: {}},
{container: "buttonItem-420",plugin: "button",option: {}},
{container: "si_80000613",plugin: "animation",option: {}},
{container: "buttonItem-421",plugin: "button",option: {}},
{container: "si_800004DF",plugin: "popupContent",option: {}},
{container: "buttonItem-422",plugin: "button",option: {}},
{container: "buttonItem-423",plugin: "button",option: {}},
{container: "si_800005D4",plugin: "animation",option: {}},
{container: "buttonItem-424",plugin: "button",option: {}},
{container: "si_80000252",plugin: "animation",option: {}},
{container: "imageItem-414",plugin: "gif",option: {}},
{container: "si_800001E9",plugin: "animation",option: {}},
{container: "si_80000254",plugin: "animation",option: {}},
{container: "si_800001EB",plugin: "animation",option: {}},
{container: "si_80000255",plugin: "animation",option: {}},
{container: "si_800005DB",plugin: "animation",option: {}},
],
"10": [{container: "si_800007FA",plugin: "animation",option: {}},
{container: "buttonItem-468",plugin: "button",option: {}},
{container: "si_80000421",plugin: "animation",option: {}},
{container: "buttonItem-469",plugin: "button",option: {}},
{container: "si_80000687",plugin: "popupContent",option: {}},
{container: "buttonItem-470",plugin: "button",option: {}},
{container: "buttonItem-471",plugin: "button",option: {}},
{container: "si_80000694",plugin: "animation",option: {}},
{container: "buttonItem-472",plugin: "button",option: {}},
{container: "si_8000068A",plugin: "animation",option: {}},
{container: "imageItem-462",plugin: "gif",option: {}},
{container: "si_8000068F",plugin: "animation",option: {}},
{container: "si_80000690",plugin: "animation",option: {}},
{container: "si_80000691",plugin: "animation",option: {}},
{container: "si_80000692",plugin: "animation",option: {}},
{container: "si_80000693",plugin: "animation",option: {}},
],
"11": [{container: "si_8000044F",plugin: "animation",option: {}},
{container: "buttonItem-512",plugin: "button",option: {}},
{container: "buttonItem-513",plugin: "button",option: {}},
{container: "buttonItem-514",plugin: "button",option: {}},
{container: "si_80000490",plugin: "popupContent",option: {}},
{container: "buttonItem-515",plugin: "button",option: {}},
{container: "buttonItem-516",plugin: "button",option: {}},
{container: "imageItem-510",plugin: "gif",option: {}},
{container: "si_8000041A",plugin: "animation",option: {}},
],
"12": [{container: "si_800007F0",plugin: "animation",option: {}},
{container: "buttonItem-553",plugin: "button",option: {}},
{container: "si_800007FE",plugin: "animation",option: {}},
{container: "buttonItem-554",plugin: "button",option: {}},
{container: "si_8000049F",plugin: "animation",option: {}},
{container: "buttonItem-555",plugin: "button",option: {}},
{container: "si_8000052E",plugin: "popupContent",option: {}},
{container: "buttonItem-556",plugin: "button",option: {}},
{container: "buttonItem-557",plugin: "button",option: {}},
{container: "si_8000037B",plugin: "animation",option: {}},
{container: "imageItem-547",plugin: "gif",option: {}},
{container: "si_80000376",plugin: "animation",option: {}},
{container: "si_80000378",plugin: "animation",option: {}},
{container: "si_80000379",plugin: "animation",option: {}},
{container: "si_80000374",plugin: "animation",option: {}},
{container: "si_800004DC",plugin: "animation",option: {}},
],
"13": [{container: "si_800007F1",plugin: "animation",option: {}},
{container: "buttonItem-601",plugin: "button",option: {}},
{container: "si_800007F5",plugin: "animation",option: {}},
{container: "buttonItem-602",plugin: "button",option: {}},
{container: "si_80000729",plugin: "animation",option: {}},
{container: "buttonItem-603",plugin: "button",option: {}},
{container: "si_80000719",plugin: "popupContent",option: {}},
{container: "buttonItem-604",plugin: "button",option: {}},
{container: "buttonItem-605",plugin: "button",option: {}},
{container: "si_80000720",plugin: "animation",option: {}},
{container: "imageItem-595",plugin: "gif",option: {}},
{container: "si_80000721",plugin: "animation",option: {}},
{container: "si_80000722",plugin: "animation",option: {}},
{container: "si_80000723",plugin: "animation",option: {}},
{container: "si_80000724",plugin: "animation",option: {}},
{container: "si_80000725",plugin: "animation",option: {}},
],
"14": [{container: "buttonItem-645",plugin: "button",option: {}},
{container: "buttonItem-646",plugin: "button",option: {}},
{container: "si_80000570",plugin: "animation",option: {}},
{container: "buttonItem-647",plugin: "button",option: {}},
{container: "si_8000057D",plugin: "popupContent",option: {}},
{container: "buttonItem-648",plugin: "button",option: {}},
{container: "buttonItem-649",plugin: "button",option: {}},
{container: "imageItem-643",plugin: "gif",option: {}},
{container: "si_80000572",plugin: "animation",option: {}},
],
"15": [{container: "si_800005F3",plugin: "animation",option: {}},
{container: "dynamicImageItem-678",plugin: "dynamicImage",option: {}},
{container: "dynamicImageItem-679",plugin: "dynamicImage",option: {}},
{container: "dynamicImageItem-680",plugin: "dynamicImage",option: {}},
{container: "dynamicImageItem-681",plugin: "dynamicImage",option: {}},
{container: "si_800005F0",plugin: "animation",option: {}},
{container: "si_800005F6",plugin: "animation",option: {}},
{container: "si_800005F9",plugin: "animation",option: {}},
{container: "si_800005FD",plugin: "animation",option: {}},
{container: "buttonItem-682",plugin: "button",option: {}},
],
};
(function () {
window.FX = window.FX || {};
var paths = [
'core/interface.js',
'core/fx.js',
'core/utils.js',
'plugins/animation.js',
'plugins/button.js',
'plugins/popupContent.js',
'plugins/imagePan.js',
'plugins/gif.js',
'plugins/dynamicImage.js',
'plugins/TimelineMax.min.js',
'plugins/TweenMax.min.js',
'plugins/animate.css',
],
baseURL = './scripts/';
for (var i = 0, pi; pi = paths[i++];) {
var extension = pi.split('.').pop();
if(extension === 'css'){
document.write('<link rel="stylesheet" type="text/css" href="' + baseURL + pi  +'"></link>');
}
else{
document.write('<script type="text/javascript" src="' + baseURL + pi + '?timestamp=' +
FX.version +
'"></script>');
}
}
})();
